# Generated by Django 3.1.1 on 2020-10-01 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urly', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortcode',
            name='shortcode',
            field=models.CharField(blank=True, max_length=6, unique=True),
        ),
    ]
