# Generated by Django 3.1.2 on 2020-10-01 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urly', '0002_auto_20201001_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortcode',
            name='shortcode',
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
