# Generated by Django 3.1.2 on 2020-10-02 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urly', '0003_auto_20201001_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortcode',
            name='lastRedirect',
            field=models.DateTimeField(default='2020-10-02T12:00:00.000Z', editable=False),
            preserve_default=False,
        ),
    ]
