# Generated by Django 3.1.2 on 2020-10-02 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urly', '0004_shortcode_lastredirect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortcode',
            name='lastRedirect',
            field=models.DateTimeField(),
        ),
    ]
