# Generated by Django 3.1.2 on 2020-10-02 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urly', '0006_auto_20201002_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortcode',
            name='redirectCount',
            field=models.IntegerField(null=True),
        ),
    ]
