# Generated by Django 3.1.2 on 2020-10-02 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urly', '0008_auto_20201002_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortcode',
            name='redirectCount',
            field=models.IntegerField(null=True),
        ),
    ]
